// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOyQOe-veAkjT3Y9Pvl8dHgGmzrkuImvY',
    appId: '1:454027838879:web:69dae71fcec2cf4bfba9aa',
    messagingSenderId: '454027838879',
    projectId: 'ameva-715ea',
    authDomain: 'ameva-715ea.firebaseapp.com',
    storageBucket: 'ameva-715ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdKSpq5iAHSV10MH8mszraPKbRVCmgfFw',
    appId: '1:454027838879:android:87efd9a3abc9278bfba9aa',
    messagingSenderId: '454027838879',
    projectId: 'ameva-715ea',
    storageBucket: 'ameva-715ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjE30HNmn4gVmGXZEREYcWRoUPo3cGJpk',
    appId: '1:454027838879:ios:05b79fa5309a6e6afba9aa',
    messagingSenderId: '454027838879',
    projectId: 'ameva-715ea',
    storageBucket: 'ameva-715ea.appspot.com',
    iosClientId: '454027838879-5lp87471b1fs4d95p684oho4uf248a26.apps.googleusercontent.com',
    iosBundleId: 'com.example.amevaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjE30HNmn4gVmGXZEREYcWRoUPo3cGJpk',
    appId: '1:454027838879:ios:05b79fa5309a6e6afba9aa',
    messagingSenderId: '454027838879',
    projectId: 'ameva-715ea',
    storageBucket: 'ameva-715ea.appspot.com',
    iosClientId: '454027838879-5lp87471b1fs4d95p684oho4uf248a26.apps.googleusercontent.com',
    iosBundleId: 'com.example.amevaStore',
  );
}
